<a href="https://colab.research.google.com/github/Shawnpeter578/practise_ML/blob/main/naive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [24]:
df = pd.read_csv("/content/titanic.csv")

In [25]:
df

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",2,male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",1,female,19.0,0,0,112053,30.0000,B42,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,"Behr, Mr. Karl Howell",1,male,26.0,0,0,111369,30.0000,C148,C,1
890,891,"Dooley, Mr. Patrick",3,male,32.0,0,0,370376,7.7500,NaN,Q,0

In [27]:
df = df.drop(["PassengerId","Name", "SibSp" , "Parch", "Ticket", "Cabin", "Embarked"], axis=1)

In [32]:
target = df.Survived
inputs = df.drop('Survived', axis=1)
inputs

     Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [29]:
dummies = pd.get_dummies(inputs.Sex)

In [46]:
dummies

     female   male
0     False   True
1      True  False
2      True  False
3      True  False
4     False   True
..      ...    ...
886   False   True
887    True  False
888    True  False
889   False   True
890   False   True

[891 rows x 2 columns]

In [49]:
inputs.drop(['male', 'female'], axis=1)

     Pclass   Age     Fare
0         3  22.0   7.2500
1         1  38.0  71.2833
2         3  26.0   7.9250
3         1  35.0  53.1000
4         3  35.0   8.0500
..      ...   ...      ...
886       2  27.0  13.0000
887       1  19.0  30.0000
888       3   NaN  23.4500
889       1  26.0  30.0000
890       3  32.0   7.7500

[891 rows x 3 columns]

In [50]:
inputs = pd.concat([inputs, dummies], axis=1)
inputs

,Pclass,Age,Fare,female,male,female,male,female,male,female,male,female,male
0,3,22.0,7.2500,False,True,False,True,False,True,False,True,False,True
1,1,38.0,71.2833,True,False,True,False,True,False,True,False,True,False
2,3,26.0,7.9250,True,False,True,False,True,False,True,False,True,False
3,1,35.0,53.1000,True,False,True,False,True,False,True,False,True,False
4,3,35.0,8.0500,False,True,False,True,False,True,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,2,27.0,13.0000,False,True,False,True,False,True,False,True,False,True
887,1,19.0,30.0000,True,False,True,False,True,False,True,False,True,False
888,3,NaN,23.4500,True,False,True,False,True,False,True,False,True,False
889,1,26.0,30.0000,False,True,False,True,False,True,False,True,False,True
890,3,32.0,7.7500,False,True,False,True,False,True,False,True,False,True

In [59]:
inputs = inputs.loc[:, ~inputs.columns.duplicated()]

In [60]:
inputs = inputs.loc[:, ~inputs.columns.duplicated(keep='first')]

In [61]:
inputs

     Pclass   Age     Fare  female   male
0         3  22.0   7.2500   False   True
1         1  38.0  71.2833    True  False
2         3  26.0   7.9250    True  False
3         1  35.0  53.1000    True  False
4         3  35.0   8.0500   False   True
..      ...   ...      ...     ...    ...
886       2  27.0  13.0000   False   True
887       1  19.0  30.0000    True  False
888       3   NaN  23.4500    True  False
889       1  26.0  30.0000   False   True
890       3  32.0   7.7500   False   True

[891 rows x 5 columns]

In [62]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [63]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())

In [64]:
inputs

     Pclass        Age     Fare  female   male
0         3  22.000000   7.2500   False   True
1         1  38.000000  71.2833    True  False
2         3  26.000000   7.9250    True  False
3         1  35.000000  53.1000    True  False
4         3  35.000000   8.0500   False   True
..      ...        ...      ...     ...    ...
886       2  27.000000  13.0000   False   True
887       1  19.000000  30.0000    True  False
888       3  29.699118  23.4500    True  False
889       1  26.000000  30.0000   False   True
890       3  32.000000   7.7500   False   True

[891 rows x 5 columns]

In [65]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2)

In [66]:
len(x_train)

712

In [67]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [68]:
model.fit(x_train, y_train)

GaussianNB()

In [69]:
model.predict(x_test)

array([1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1])

In [75]:
model.score(x_test, y_test)

0.7932960893854749

In [77]:
x_test[:10]

     Pclass        Age      Fare  female   male
435       1  14.000000  120.0000    True  False
316       2  24.000000   26.0000    True  False
497       3  29.699118   15.1000   False   True
602       1  29.699118   42.4000   False   True
278       3   7.000000   29.1250   False   True
879       1  56.000000   83.1583    True  False
824       3   2.000000   39.6875   False   True
802       1  11.000000  120.0000   False   True
263       1  40.000000    0.0000   False   True
15        2  55.000000   16.0000    True  False

In [78]:
y_test[:10]

435    1
316    1
497    0
602    0
278    0
879    1
824    0
802    1
263    0
15     1
Name: Survived, dtype: int64

In [79]:
model.predict(x_test[:10])

array([1, 1, 0, 0, 0, 1, 0, 1, 0, 1])

In [80]:
model.predict_proba(x_test[:10])

array([[1.63170591e-04, 9.99836829e-01],
       [2.37752850e-02, 9.76224715e-01],
       [9.89749264e-01, 1.02507364e-02],
       [9.09446988e-01, 9.05530116e-02],
       [9.81283739e-01, 1.87162613e-02],
       [1.63946762e-03, 9.98360532e-01],
       [9.74226755e-01, 2.57732454e-02],
       [1.95381925e-01, 8.04618075e-01],
       [9.26215456e-01, 7.37845435e-02],
       [2.54148454e-02, 9.74585155e-01]])